### ISSUE TITLE
Question about SEI support

### ISSUE THREAD

**Issue by jhnbwrs** [chemag/h265nal#19]
SEI nal parsing is clearly mentioned as a TODO.  Is this something you are looking to work on anytime soon?  If not, do you have any words of advice for someone who might be interested in adding it?

**Comment by chemag** [comment]
Look at the AUD parser. Start with src/h265_sei_parser.[h|cc] and test/h265_sei_parser_unittest.cc from the aud versions. Implement 1x of the SEI subtypes, including a test. For the test, look for h265 sources that include SEI NALUs. In fact, I'd suggest to implement whatever SEI you see in any h265 file you can find.

**Comment by jhnbwrs** [comment]
> Look at the AUD parser. Start with src/h265_sei_parser.[h|cc] and test/h265_sei_parser_unittest.cc from the aud versions. Implement 1x of the SEI subtypes, including a test. For the test, look for h265 sources that include SEI NALUs. In fact, I'd suggest to implement whatever SEI you see in any h265 file you can find.

Ah yes, finding samples is something I haven't yet done.  I am most interested in captions carried in SEIs though.  That is what I will be looking for first.  If you happen to know of some feel free to share :)

**Comment by chemag** [comment]
In my experience, if it exists, it's in the videolan format samples:
      - https://streams.videolan.org/samples/
      - https://streams.videolan.org/streams/
