### ISSUE TITLE
Set kLog2MaxMvLengthHorizontalMax to 16

### ISSUE THREAD

**Issue by yannlandry** [chemag/h265nal#25]
The maximum value for `log2_max_mv_length_horizontal` is given by `kLog2MaxMvLengthHorizontalMax` in `include/h265_vui_parameters_parser.h` and is currently set to 15 which is in line with the current H.265 spec but versions of the H.265 spec pre-February 2018 (e.g. [version 12/2016](https://www.itu.int/rec/T-REC-H.265-201612-S/en), section E.3.1, page 388) specify that the maximum value for `log2_max_mv_length_horizontal` may be 16 and not 15.

A suggestion would be to increase the value of `kLog2MaxMvLengthHorizontalMax` to 16 to better work with streams that conform to older specs of H.265, even though the older specs are no longer in effect.

**Comment by chemag** [comment]
Fixed in 354da752. 

Please take a look
