### ISSUE TITLE
What about absl library ?

### ISSUE THREAD

**Issue by Consti10** [chemag/h265nal#3]
Hello,
First of all, really cool library ! 
I didn't find it at first, started writing my own h265 parser but after 4h I was still not done with the sps parser :)
So happy I found this repo.

However, I find these references to the 'absl' library in code but the readme doesn't say anything about dependency on absl.

Do I have to add the source code of absl manually when compiling ? (I am going to use android ndk / CMake )

**Comment by Consti10** [comment]
E.g. why don't you use std::optional instead of absl ?

**Comment by Consti10** [comment]
It looks to me like the only part of absl used in this library is absl::optional from https://github.com/abseil/abseil-cpp/blob/master/absl/types/optional.h

**Comment by Consti10** [comment]
I think i found a workaround:
I added a file called 'optional.h' in src/absl/types

Its content is as follows:
`#ifndef MY_OPTIONAL_ABS
#define MY_OPTIONAL_ABS

#include <optional>

namespace absl{
    template<class T>
    using optional=std::optional<T>;

    //template<class T>
    //using nullopt=std::optional;
    //typedef decltype(nullopt) nullptr_t;
    //inline constexpr std::nullopt nullopt{/*unspecified*/};
    //struct nullopt_t{/* see description */};
    inline constexpr auto nullopt=std::nullopt;
}

#endif //MY_OPTIONAL_ABS`

**Comment by Consti10** [comment]
This is how I use it :
https://github.com/Consti10/LiveVideo10ms/tree/master/VideoCore/libs/h265nal

**Comment by chemag** [comment]
std::optional is C++17, which I don't have. 

In order to build the original library, you need abseil (absl) support. Dunno how to make it work in Android (but I'm interested in knowing if you find out).

Your solution just makes absl::optional (and absl::nullopt) an alias for std::optional (and std::nullopt), which means it's c++17-only.

**Comment by Consti10** [comment]
Thanks for the clarification.
Android ndk supports C++17 without problems, so I think my workaround is the easiest thing to do.
It certainly wouldn't be a prolem compiling absl on android, but why bother when std::optional is available and your library works fine on it.
