### ISSUE TITLE
h265nal and h264 in one project

### ISSUE THREAD

**Issue by khozaei** [chemag/h265nal#30]
My project failed to compile due to a naming conflict: both the h264nal and h265nal libraries include a file named `rtc_common.h`. This prevents successful compilation when attempting to use both libraries within the same project.
The error:
```
/home/noa-pc/code/amin/jac_noa_all_swc/build/cmake-build-debug-default_toolchain/clang-aos_gea-aarch64/h265nal/src/../include/h265_sps_scc_extension_parser.h:63:7: error: unknown type name 'BitBuffer'; did you mean 'h264nal::BitBuffer'?
      BitBuffer* bit_buffer, uint32_t chroma_format_idc,
      ^~~~~~~~~
      h264nal::BitBuffer
/home/noa-pc/code/amin/jac_noa_all_swc/build/cmake-build-debug-default_toolchain/clang-aos_gea-aarch64/h264nal/src/../include/rtc_common.h:68:7: note: 'h264nal::BitBuffer' declared here
```

**Comment by chemag** [comment]
This sounds to me like a library import issue, either in your side or in the library's side. Importing 2x libraries that contain a header file with the same name should be ok.

**Comment by chemag** [comment]
I actually had to do exactly this in https://github.com/chemag/liblcvm. I did the necessary fixes to h265nal (and h264nal) so that it works. Please take a look
