### ISSUE TITLE
Get video width height in px from SPS

### ISSUE THREAD

**Issue by Consti10** [chemag/h265nal#4]
Hello,
Do you know how to get the video width and height from a parsed h265 sps ?
For h264 it is something like this:
```
std::array<int,2> getWidthHeightPx()const{
            int Width = ((parsed.pic_width_in_mbs_minus1 +1)*16) -parsed.frame_crop_right_offset *2 -parsed.frame_crop_left_offset *2;
            int Height = ((2 -parsed.frame_mbs_only_flag)* (parsed.pic_height_in_map_units_minus1 +1) * 16) - (parsed.frame_crop_bottom_offset* 2) - (parsed.frame_crop_top_offset* 2);
            return {Width,Height};
        }
```

But in h265 fields like `pic_width_in_mbs_minus1` are missing. (or renamed ? )

**Comment by chemag** [comment]
look for "1280" in https://github.com/chemag/h265nal/blob/master/test/h265_sps_parser_unittest.cc

**Comment by Consti10** [comment]
For a video stream of size 180*120 I get the following values for pic_width_in_luma_samples / pic_height_in_luma_samples:
184*120
E.g. the video width matches alomst, the video height matches.

**Comment by chemag** [comment]
> For a video stream of size 180x120 I get the following values for pic_width_in_luma_samples / pic_height_in_luma_samples:
> 184x120
> E.g. the video width matches alomst, the video height matches.
I doubt your width is 180 (180 is not a multiple of 8).

**Comment by chemag** [comment]
> > For a video stream of size 180x120 I get the following values for pic_width_in_luma_samples / pic_height_in_luma_samples:
> > 184x120
> > E.g. the video width matches alomst, the video height matches.
> > I doubt your width is 180 (180 is not a multiple of 8).

IIRC, there is a way to have 2 different dimensions, the encoded ones, and the "active" ones (which sort of defines padding). 

Check the standard
